name := "soap"
version := "0.2.0"
scalaVersion := "2.12.7"
organization := "com.hwaipy"
libraryDependencies += "org.scala-lang" % "scala-reflect" % "2.12.7"
libraryDependencies += "org.scala-lang" % "scala-compiler" % "2.12.7"
libraryDependencies += "org.scala-lang.modules" %% "scala-xml" % "1.1.1"
libraryDependencies += "com.hwaipy" %% "hydrogen" % "0.3.0"
libraryDependencies += "com.xeiam.xchart" % "xchart" % "2.5.1" exclude("de.erichseifert.vectorgraphics2d", "VectorGraphics2D")
libraryDependencies += "org.apache.commons" % "commons-math3" % "3.6.1"
libraryDependencies += "org.rxtx" % "rxtx" % "2.1.7"
libraryDependencies += "org.jscience" % "jscience" % "4.3.1"
libraryDependencies += "org.scalanlp" %% "breeze" % "1.0-RC2"
libraryDependencies += "org.scalanlp" %% "breeze-natives" % "1.0-RC2"
libraryDependencies += "com.hydra" %% "sydra" % "0.6.0"
scalacOptions ++= Seq("-feature")
scalacOptions ++= Seq("-deprecation")
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.5" % "test"
